version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: codebook_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    networks:
      - codebook-network

  # Backend Service
  backend:
    build:
      context: ./backend
    container_name: codebook_backend
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      PORT: 5000
    depends_on:
      - mysql
    networks:
      - codebook-network
    command: sh -c "/wait-for mysql:3306 -- npm start"
volumes:
  mysql_data:

networks:
  codebook-network:
    driver: bridge